### ISSUE TITLE
404 on all O'Reilly links

### ISSUE THREAD

**Issue by pysr1** [jphall663/interpretable_machine_learning_with_python#10]
404 on all O'Reilly links

**Comment by jphall663** [comment]
Thanks - will check this out.

**Comment by jphall663** [comment]
In the meantime - try aquarium?

**Comment by jphall663** [comment]
So I joined Safari and searched for the videos ... and I cannot find them. Maybe O'Reilly decided that they are out of date? Which they kind of are ... 

I'm closing this for now. Hopefully either aquarium, docker or virtualenv (pending) installs will work for you. Sorry for the inconvenience. 

Will update README to reflect this as well.
