### ISSUE TITLE
Please post the slides from Youtube video https://www.youtube.com/watch?v=Q8rTrmqUQsU

### ISSUE THREAD

**Issue by wnmills3** [jphall663/interpretable_machine_learning_with_python#3]
I enjoyed your presentation I found on Youtube from a meet up in late April. You'd mentioned the pdf for the talk would be posted but from Youtube it is unable to be found. Could you please post here or there? Thanks in advance.

**Comment by jphall663** [comment]
Oh great - I believe everything is here: https://github.com/h2oai/h2o-meetups/blob/master/2018_04_30_NYC_MLI_good_bad_ugly/MLI_good_bad_ugly.pdf

Also you may be interested in these repos:
https://github.com/h2oai/mli-resources
https://github.com/jphall663/awesome-machine-learning-interpretability
