### ISSUE TITLE
O'Reilly Safari videos not working

### ISSUE THREAD

**Issue by sayakpaul** [jphall663/interpretable_machine_learning_with_python#7]
Hi @jphall663.

Firstly, a huge shout out to you for this repo. I wanted to tell you that the videos that you linked are not working.

For your reference: 
https://www.useloom.com/share/3c31bf9b1e4c44608f2b6940230cc11a 

It happens with the other three video links as well.

**Comment by jphall663** [comment]
Hmmm ... maybe it was a temporary thing? Maybe it has to do with your location? It works for me today:
![selection_101](https://user-images.githubusercontent.com/5297912/51803466-87429c00-2223-11e9-9b8c-1501df715b45.png)

**Comment by sayakpaul** [comment]
Yes, works today. Thanks!
